apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: demo-mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-secrets
    key: MARIADB_ROOT_PASSWORD
  storage:
    size: 1Gi

  # Replication
  replicas: 3
  replication:
    enabled: true
 
  primaryService:
    type: ClusterIP
 
  secondaryService:
    type: ClusterIP