apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- 01-secrets.yml
- 02-mariadb.yml 
# kubectl get mariadbs
# kubectl get svc
# kubectl exec -it demo-mariadb-0 -- mariadb -uroot -pverysecret -hdemo-mariadb-primary -e 'show replica hosts;'
- 03-database.yml
# kubectl exec -it demo-mariadb-0 -- mariadb -udemo -psecret demo -e 'show databases;'